# Generated by Django 3.2.6 on 2021-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
