# Generated by Django 3.2.6 on 2021-09-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0017_auto_20210905_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unreadmessages',
            old_name='messages',
            new_name='message',
        ),
    ]
