# Generated by Django 3.2.6 on 2022-03-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0018_rename_messages_unreadmessages_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_added',)},
        ),
    ]
