# Generated by Django 3.2.6 on 2021-08-09 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0003_auto_20210809_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='auth_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
