# Generated by Django 3.2.6 on 2021-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_auto_20210813_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='./Default_avatar.png', upload_to='./images'),
        ),
    ]
